print ("ALDEAN MATTHEW ALMONTE")
print ("Brgy. Pag-asa Santa Cruz, Marinduque")
print ("February 13, 2003")
print ("BSI/T")
print ("2")
print ("C")
print ("Playing online games")
print ("Playing Basketball")
print ("Building Gundam Figures")
print ("Watching Movies")
print ("Scroliing on Facebook")